name: 'spring-boot-leaderboard'
services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - microservices-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres:
    driver: local

networks:
  microservices-net:
    driver: bridge